// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/feed/posts": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieves a feed of posts for the authenticated user. Supports two sorting modes: chronological (default) and by popularity (score). Uses cursor-based pagination for efficient data retrieval.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Feed"
                ],
                "summary": "Get feed posts",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Profile ID of the viewer (for feed and vote information)",
                        "name": "X-Viewer-Profile-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Sorting method: 'chronological' (default) or 'score'/'popular' (by popularity)",
                        "name": "sort",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "format": "date-time",
                        "description": "Pagination cursor (RFC3339 timestamp) for chronological sorting",
                        "name": "cursor",
                        "in": "query"
                    },
                    {
                        "minimum": 0,
                        "type": "integer",
                        "description": "Pagination cursor (score value) for score-based sorting",
                        "name": "score_cursor",
                        "in": "query"
                    },
                    {
                        "maximum": 100,
                        "minimum": 1,
                        "type": "integer",
                        "default": 20,
                        "description": "Number of posts to return (1-100, default: 20)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Feed posts retrieved successfully with pagination metadata",
                        "schema": {
                            "$ref": "#/definitions/feed_posts.Response"
                        }
                    },
                    "400": {
                        "description": "Bad request - invalid parameters or malformed request",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized - missing or invalid authentication headers",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "Internal server error - database or service failure",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/posts": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Creates a new post with images and tags. Tags are validated and created in tag service. Images must exist in image service.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Posts"
                ],
                "summary": "Create a new post",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Profile ID of the post creator",
                        "name": "X-Profile-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Post creation data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/posts_create.Request"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Post created successfully",
                        "schema": {
                            "$ref": "#/definitions/posts_create.Response"
                        }
                    },
                    "400": {
                        "description": "Bad request - invalid input parameters or validation failed",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized - missing or invalid authentication",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "Internal server error - database or service failure",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/posts/user/all": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieves all posts for a specific user with cursor-based pagination. Returns public posts for any viewer, but includes drafts if the viewer is the post owner. Includes detailed post information, images, tags, and vote status.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Posts"
                ],
                "summary": "Get all posts for a user",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Profile ID of the user whose posts are being retrieved",
                        "name": "X-Profile-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Profile ID of the viewer (used for access control and vote information)",
                        "name": "X-Viewer-Profile-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "format": "date-time",
                        "description": "Pagination cursor (RFC3339 timestamp) - returns posts created before this time",
                        "name": "cursor",
                        "in": "query"
                    },
                    {
                        "maximum": 100,
                        "minimum": 1,
                        "type": "integer",
                        "default": 20,
                        "description": "Number of posts to return (1-100, default: 20)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Posts retrieved successfully with pagination metadata",
                        "schema": {
                            "$ref": "#/definitions/posts_user_all.Response"
                        }
                    },
                    "400": {
                        "description": "Bad request - invalid parameters or malformed request",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized - missing or invalid authentication headers",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "Internal server error - database or service failure",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/posts/{post_id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieves detailed information about a specific post including images, tags, votes, and metadata. Draft posts are only accessible by the post owner. Returns comprehensive post data with user-specific vote information.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Posts"
                ],
                "summary": "Get a specific post by ID",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Profile ID of the viewer (used for access control and vote information)",
                        "name": "X-Viewer-Profile-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Post ID to retrieve",
                        "name": "post_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Post retrieved successfully",
                        "schema": {
                            "$ref": "#/definitions/posts_get.Response"
                        }
                    },
                    "400": {
                        "description": "Bad request - invalid post ID format",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized - missing or invalid authentication",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "404": {
                        "description": "Post not found - either doesn't exist or viewer doesn't have access",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "Internal server error - database or service failure",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Deletes a post. Only the post owner can delete their own posts. This action is irreversible and removes all associated data including images, tags, and votes.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Posts"
                ],
                "summary": "Delete a post",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Profile ID of the post owner",
                        "name": "X-Profile-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Post ID to delete",
                        "name": "post_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Post deleted successfully",
                        "schema": {
                            "$ref": "#/definitions/posts_delete.Response"
                        }
                    },
                    "400": {
                        "description": "Bad request - invalid parameters or missing headers",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "403": {
                        "description": "Forbidden - user is not the owner of the post",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "404": {
                        "description": "Post not found",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "Internal server error - database failure",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/posts/{post_id}/images/{image_id}/vote": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Allows users to upvote (1), downvote (-1), or remove vote (0) on a specific image within a published post. Images in draft posts cannot be voted on.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Posts"
                ],
                "summary": "Vote on an image within a post",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Profile ID of the voter",
                        "name": "X-Profile-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Post ID containing the image",
                        "name": "post_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Image ID to vote on",
                        "name": "image_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Vote value",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/images_vote.Request"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Vote recorded successfully with updated image scores",
                        "schema": {
                            "$ref": "#/definitions/images_vote.Response"
                        }
                    },
                    "400": {
                        "description": "Bad request - invalid vote value, invalid parameters, or missing headers",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "403": {
                        "description": "Forbidden - attempting to vote on image in draft post",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "404": {
                        "description": "Image not found",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "Internal server error - database failure",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/posts/{post_id}/publish": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Publishes a draft post, making it publicly visible. Only the post owner can publish their own draft posts. Published posts cannot be re-published.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Posts"
                ],
                "summary": "Publish a draft post",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Profile ID of the post owner",
                        "name": "X-Profile-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Post ID to publish",
                        "name": "post_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Post published successfully",
                        "schema": {
                            "$ref": "#/definitions/posts_publish.Response"
                        }
                    },
                    "400": {
                        "description": "Bad request - invalid parameters, post already published, or missing headers",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "403": {
                        "description": "Forbidden - user is not the owner of the post",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "404": {
                        "description": "Post not found",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "Internal server error - database failure",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/posts/{post_id}/vote": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Allows users to upvote (1), downvote (-1), or remove vote (0) on a published post. Draft posts cannot be voted on.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Posts"
                ],
                "summary": "Vote on a post",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Profile ID of the voter",
                        "name": "X-Profile-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Post ID to vote on",
                        "name": "post_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Vote value",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/posts_vote.Request"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Vote recorded successfully with updated scores",
                        "schema": {
                            "$ref": "#/definitions/posts_vote.Response"
                        }
                    },
                    "400": {
                        "description": "Bad request - invalid vote value, invalid parameters, or missing headers",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "403": {
                        "description": "Forbidden - attempting to vote on draft post",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "404": {
                        "description": "Post not found",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "Internal server error - database failure",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/search/images": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Searches for images based on tag relevance across all posts. Images are ranked by how many of the requested tags they contain. Supports pagination using a combined cursor of relevance score and timestamp. Tags are validated and created if they don't exist.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Search"
                ],
                "summary": "Search images by tags",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Profile ID of the viewer (for vote information)",
                        "name": "X-Viewer-Profile-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Comma-separated list of tags to search for",
                        "name": "tags",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Pagination cursor in format 'relevance_timestamp' or just 'timestamp'",
                        "name": "cursor",
                        "in": "query"
                    },
                    {
                        "maximum": 100,
                        "minimum": 1,
                        "type": "integer",
                        "default": 20,
                        "description": "Number of images to return (1-100, default: 20)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Images retrieved successfully with relevance scoring and pagination",
                        "schema": {
                            "$ref": "#/definitions/search_images.Response"
                        }
                    },
                    "400": {
                        "description": "Bad request - missing tags parameter or invalid cursor format",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized - missing or invalid authentication headers",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "Internal server error - database or service failure",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/search/posts": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Searches for posts based on tag relevance. Posts are ranked by how many of the requested tags they contain. Supports pagination using a combined cursor of relevance score and timestamp. Tags are validated and created if they don't exist.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Search"
                ],
                "summary": "Search posts by tags",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Profile ID of the viewer (for vote information)",
                        "name": "X-Viewer-Profile-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Comma-separated list of tags to search for",
                        "name": "tags",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Pagination cursor in format 'relevance_timestamp' or just 'timestamp'",
                        "name": "cursor",
                        "in": "query"
                    },
                    {
                        "maximum": 100,
                        "minimum": 1,
                        "type": "integer",
                        "default": 20,
                        "description": "Number of posts to return (1-100, default: 20)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Posts retrieved successfully with relevance scoring and pagination",
                        "schema": {
                            "$ref": "#/definitions/search_posts.Response"
                        }
                    },
                    "400": {
                        "description": "Bad request - missing tags parameter or invalid cursor format",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized - missing or invalid authentication headers",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "Internal server error - database or service failure",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "feed_posts.Response": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "has_next": {
                    "type": "boolean"
                },
                "limit": {
                    "type": "integer"
                },
                "next_cursor": {
                    "type": "string"
                },
                "next_score": {
                    "type": "integer"
                },
                "posts": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/post.FeedPostResponse"
                    }
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "image.Image": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "extension": {
                    "type": "string"
                },
                "file_url": {
                    "type": "string"
                },
                "height": {
                    "type": "integer"
                },
                "image_id": {
                    "type": "string"
                },
                "profile_id": {
                    "type": "string"
                },
                "score": {
                    "type": "integer"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/tag.Tag"
                    }
                },
                "user_vote": {
                    "type": "integer"
                },
                "width": {
                    "type": "integer"
                }
            }
        },
        "image.ImageResponseWithRelevance": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "extension": {
                    "type": "string"
                },
                "file_url": {
                    "type": "string"
                },
                "height": {
                    "type": "integer"
                },
                "image_id": {
                    "type": "string"
                },
                "post_id": {
                    "type": "string"
                },
                "profile_id": {
                    "type": "string"
                },
                "relevance": {
                    "type": "integer"
                },
                "score": {
                    "type": "integer"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/tag.Tag"
                    }
                },
                "user_vote": {
                    "type": "integer"
                },
                "width": {
                    "type": "integer"
                }
            }
        },
        "image.ImageWithTags": {
            "type": "object",
            "properties": {
                "image_id": {
                    "type": "string"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/tag.Tag"
                    }
                }
            }
        },
        "images_vote.Request": {
            "type": "object",
            "properties": {
                "value": {
                    "type": "integer"
                }
            }
        },
        "images_vote.Response": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "image_id": {
                    "type": "string"
                },
                "new_score": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                },
                "user_vote": {
                    "type": "integer"
                }
            }
        },
        "post.CreatedPostResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "images": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/image.ImageWithTags"
                    }
                },
                "is_draft": {
                    "type": "boolean"
                },
                "profile_id": {
                    "type": "string"
                },
                "score": {
                    "type": "integer"
                },
                "text": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_vote": {
                    "type": "integer"
                }
            }
        },
        "post.FeedPostResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "images": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/image.Image"
                    }
                },
                "is_draft": {
                    "type": "boolean"
                },
                "profile_id": {
                    "type": "string"
                },
                "score": {
                    "type": "integer"
                },
                "text": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_vote": {
                    "type": "integer"
                }
            }
        },
        "post.PostResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "images": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/image.Image"
                    }
                },
                "is_draft": {
                    "type": "boolean"
                },
                "profile_id": {
                    "type": "string"
                },
                "score": {
                    "type": "integer"
                },
                "text": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_vote": {
                    "type": "integer"
                }
            }
        },
        "post.PostResponseWithRelevance": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "images": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/image.Image"
                    }
                },
                "is_draft": {
                    "type": "boolean"
                },
                "profile_id": {
                    "type": "string"
                },
                "relevance": {
                    "type": "integer"
                },
                "score": {
                    "type": "integer"
                },
                "text": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_vote": {
                    "type": "integer"
                }
            }
        },
        "posts_create.Request": {
            "type": "object",
            "properties": {
                "image_ids": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "is_draft": {
                    "type": "boolean"
                },
                "tags": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    }
                },
                "text": {
                    "type": "string"
                }
            }
        },
        "posts_create.Response": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "post": {
                    "$ref": "#/definitions/post.CreatedPostResponse"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "posts_delete.Response": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "posts_get.Response": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "post": {
                    "$ref": "#/definitions/post.PostResponse"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "posts_publish.Response": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "posts_user_all.Response": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "has_next": {
                    "type": "boolean"
                },
                "limit": {
                    "type": "integer"
                },
                "next_cursor": {
                    "type": "string"
                },
                "posts": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/post.PostResponse"
                    }
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "posts_vote.Request": {
            "type": "object",
            "properties": {
                "value": {
                    "type": "integer"
                }
            }
        },
        "posts_vote.Response": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "new_score": {
                    "type": "integer"
                },
                "post_id": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "user_vote": {
                    "type": "integer"
                }
            }
        },
        "response.Response": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "search_images.Response": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "has_next": {
                    "type": "boolean"
                },
                "images": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/image.ImageResponseWithRelevance"
                    }
                },
                "limit": {
                    "type": "integer"
                },
                "next_cursor": {
                    "type": "string"
                },
                "next_relevance": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "search_posts.Response": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "has_next": {
                    "type": "boolean"
                },
                "limit": {
                    "type": "integer"
                },
                "next_cursor": {
                    "type": "string"
                },
                "next_relevance": {
                    "type": "integer"
                },
                "posts": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/post.PostResponseWithRelevance"
                    }
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "tag.Tag": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        }
    },
    "tags": [
        {
            "description": "\"Post operations: create post, get single post, vote post/image, delete, etc\"",
            "name": "Posts"
        },
        {
            "description": "\"Feed operations: get content for the user\"",
            "name": "Feed"
        },
        {
            "description": "\"Search operations: tag search for posts/images\"",
            "name": "Search"
        }
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8095",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Feed Microservice API",
	Description:      "Microservice for managing posts, post images, voting, feed, and search functionality",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
